# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-05-15 07:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='post',
            name='description',
            field=models.TextField(default='please enter the description'),
            preserve_default=False,
        ),
    ]
